# Generated by Django 3.2.7 on 2022-05-21 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
