# Generated by Django 3.2.7 on 2022-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
