# Generated by Django 4.0.4 on 2022-05-21 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='guid',
            field=models.CharField(default=uuid.UUID('5cecd21e-847d-42a0-a357-627bdd56f1fd'), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
