# Generated by Django 4.0.4 on 2022-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
