# Generated by Django 3.2.7 on 2022-05-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_added_tables_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='label',
            field=models.CharField(default='T1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='cafe.cafe'),
        ),
    ]
