# Generated by Django 3.2.7 on 2022-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20220513_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(choices=[('pi', 'Pink'), ('or', 'Orange'), ('gr', 'Green'), ('rd', 'Red'), ('wt', 'White'), ('yl', 'Yellow'), ('bl', 'Blue'), ('go', 'Gold')], default='rd', max_length=2),
            preserve_default=False,
        ),
    ]
