# Generated by Django 3.2.7 on 2022-05-21 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20220522_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='guid',
            field=models.CharField(default=uuid.UUID('f0f21567-626e-4d1e-8f70-22aed0919573'), max_length=50, unique=True),
        ),
    ]
