# Generated by Django 3.2.7 on 2022-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_table_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('orange', 'orange'), ('green', 'green'), ('red', 'red'), ('white', 'white'), ('yellow', 'yellow'), ('blue', 'blue'), ('gold', 'gold')], default='red', max_length=50),
        ),
    ]
