# Generated by Django 3.2.7 on 2022-05-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='color',
            field=models.CharField(default='unselected-color', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('tables', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.table')),
            ],
        ),
    ]
