# Generated by Django 3.2.7 on 2022-05-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20220521_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='tables',
        ),
        migrations.AddField(
            model_name='record',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='cafe.table'),
        ),
    ]
