# Generated by Django 3.2.7 on 2022-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_record_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
